# Generated by Django 5.0.7 on 2024-08-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_article_body_alter_article_body_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Published')], default='df', max_length=15, verbose_name='Status'),
        ),
    ]
